home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

linphoneapp/urls.py
from django.conf.urls import url

from . import views

app_name = 'linphoneapp'
urlpatterns = [
    url(r'^$', views.linphoneapp, name='linphoneapp'),
]

typiremote/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('home.urls')),
    url(r'^linphoneapp/', include('linphoneapp.urls')),
    url(r'^media/', include('media.urls')),
    url(r'^settings/', include('settings.urls')),
    url(r'^console/', include('console.urls')),
    url(r'^admin/', admin.site.urls),
]

linphoneapp/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class LinphoneAccount(models.Model):
    name = models.CharField(max_length=50)
    sip_account = models.CharField(max_length=200)
    
    def __str__(self):
        return "name: %s, sip_account: %s" % (self.name,  self.sip_account)
    

linphoneapp/views.py
from django.shortcuts import render
from django.db.models import Q
from .models import LinphoneAccount
# Create your views here.

def linphoneapp(request):
    linphone_acct_list = LinphoneAccount.objects.order_by('name')
    context = {'linphone_acct_list': linphone_acct_list}
    
    if "addLinphoneAcctSubmit" in request.POST:
        newacct_name = request.POST["newacct_name"]
        newacct_sip = request.POST["newacct_sip"]
        if not newacct_name:
            context['error_message'] = "Enter a name"
            return render(request,  'linphoneapp/linphoneapp.html',  context)
        if not newacct_sip:
            context['error_message'] = "Enter a SIP account"
            return render(request,  'linphoneapp/linphoneapp.html',  context)
        l = LinphoneAccount.objects.filter(Q(name=newacct_name) | Q(sip_account=newacct_sip))
        if l:
            context['error_message'] = "Account already in the list"
            return render(request,  'linphoneapp/linphoneapp.html',  context)
        l = LinphoneAccount(name=newacct_name, sip_account=newacct_sip)
        l.save()
    
    if "editLinphoneAcctSubmit" in request.POST:
        editacct_id = request.POST["editacct_id"]
        editacct_name = request.POST["editacct_name"]
        editacct_sip = request.POST["editacct_sip"]
        l = LinphoneAccount.objects.get(pk=editacct_id)
        l.name = editacct_name
        l.sip_account = editacct_sip
        l.save()
        
    if "deleteLinphoneAcctSubmit" in request.POST:
        deleteacct_id = request.POST["deleteacct_id"]
        l = LinphoneAccount.objects.get(pk=deleteacct_id)
        l.delete()
    
    return render(request,  'linphoneapp/linphoneapp.html',  context)

linphoneapp/templates/linphoneapp/linphoneapp.html
<!DOCTYPE html>
<html lang="en">

<head>
<title>Video Manager</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'styles/linphoneapp.css' %}" />
<!--
<link rel="stylesheet" href="css/bootstrap.min.css">
<link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="styles/default-styles.css">
<link rel="stylesheet" type="text/css" href="styles/home.css">
<link rel="stylesheet" type="text/css" href="styles/footer-default.css">
-->
</head>

<body>

    <nav class="navbar sticky-top navbar-light bg-light">
      <div class="container-fluid">
        <div class=" navbar-header navbar-default">
          <div class="mycontainer">
            <a href="/"><img src="{% static 'images/backbutton.png' %}"/></a>
            &nbsp;Back
          </div>
        </div>
      </div>           
    </nav>
    
    <div class="container toplevelContainer">
        <div class="row">
            <div class="col"></div>
            <div class="col-10 col-sm-8 col-md-6 col-lg-4">
                <div class="mainTitle"><h5><strong>Add an Existing Linphone Account</strong><h5></div>
                <form action="{% url 'linphoneapp:linphoneapp' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="inputName">Name</label>
                        <input type="text" class="form-control" name="newacct_name" id="inputName" aria-describedby="nameHelp" placeholder="Enter name" required/>
                        <small id="nameHelp" class="form-text text-muted">This will be the keyword name whenever you want to call this account.</small>
                    </div>
                    <div class="form-group">
                        <label for="inputSIPAccount">SIP Account</label>
                        <input type="email" class="form-control" name="newacct_sip" id="inputSIPAccount" aria-describedby="sipHelp" placeholder="Ex. username@sip.linphone.org" required/>
                        <small id="sipHelp" class="form-text text-muted">SIP Account needs to be already a valid registered account.</small>
                    </div>
                    <div class="errormsg">{% if error_message %}{{ error_message }}{% endif %}</div>
                    <button type="submit" class="btn btn-primary" id="addB" name="addLinphoneAcctSubmit" value="Add Linphone Acct">Add Account</button>
                </form>
            </div>
            <div class="col"></div>
        </div>
    </div>
    <div class="container tableContainer">
        <div class="row">
            <div class="col"></div>
            <div class="col-12 col-sm-10 col-md-8 col-lg-6">
                <table class="table table-sm table-hover table-bordered" id="linphoneaccttable">
                  <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Name</th>
                      <th scope="col">SIP Account</th>
                      <th scope="col">Options</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% if linphone_acct_list %}
                        {% for linphone_acct in linphone_acct_list %}
                            <tr>
                              <th scope="row">{{ forloop.counter }}</th>
                              <td>{{ linphone_acct.name }}</td>
                              <td>{{ linphone_acct.sip_account }}</td>
                              <td>
                                <a data-toggle="modal" data-target="#editLinphoneAcctModal" data-acctid="{{ linphone_acct.id }}" data-name="{{ linphone_acct.name }}" data-sipacct="{{ linphone_acct.sip_account }}" data-backdrop="static" data-keyboard="false" href="#">Edit</a>
                                <a data-toggle="modal" data-target="#deleteLinphoneAcctModal" data-backdrop="static" data-keyboard="false" href="#" data-acctid="{{ linphone_acct.id }}" data-name="{{ linphone_acct.name }}">Delete</a>
                              </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                    You linphone contact list is empty.
                    {% endif %}
                  </tbody>
                </table>
            </div>
            <div class="col"></div>
        </div>
    </div>
    
    <!-- Delete Linphone Account Modal -->
    <div class="modal fade" id="deleteLinphoneAcctModal" tabindex="-1" role="dialog" aria-labelledby="deleteLinphoneAcctModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteLinphoneAcctModalLabel">Delete Linphone Account</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body" id="modal-body-div"></div>
            <form action="{% url 'linphoneapp:linphoneapp' %}" method="post">
                {% csrf_token %}
                <input type="hidden" class="form-control" id="delete-id" name="deleteacct_id">
                <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
                <button type="submit" name="deleteLinphoneAcctSubmit" class="btn btn-success">Yes</button>
                </div>
            </form>
        </div>
      </div>
    </div>
    
    <div class="modal fade" id="editLinphoneAcctModal" tabindex="-1" role="dialog" aria-labelledby="editLinphoneAcctModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="editLinphoneAcctModalLabel">Edit Linphone Account</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <form action="{% url 'linphoneapp:linphoneapp' %}" method="post" id="editAcctForm">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="form-group">
                        <label for="edit-name" class="col-form-label">Name:</label>
                        <input type="text" class="form-control" id="edit-name" name="editacct_name" required>
                        </div>
                        <div class="form-group">
                        <label for="edit-sipAccount" class="col-form-label">SIP Account:</label>
                        <input type="text" class="form-control" id="edit-sipAccount" name="editacct_sip" required>
                        <input type="hidden" class="form-control" id="edit-id" name="editacct_id">
                        </div>
                        <div class="errormsg" id="errormsg-edit-acct"></div>
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" name="editLinphoneAcctSubmit" value="Edit Linphone Acct" class="btn btn-primary">Save Changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <script>
        $('#editLinphoneAcctModal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget);
            var id = button.data('acctid');
            var name = button.data('name');
            var sip_acct = button.data('sipacct');
            $('#edit-name').val(name);
            $('#edit-sipAccount').val(sip_acct);
            $('#edit-id').val(id);
        })
        
        $('#deleteLinphoneAcctModal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget);
            var id = button.data('acctid');
            var name = button.data('name');
            $('#delete-id').val(id);
            $('#modal-body-div').html("SIP Account with name \"" + name + "\" will be deleted from your contact list. Continue?");
        })
        
        $('#editAcctForm').submit(function(e){
            var table = document.getElementById("linphoneaccttable");
            for (var i = 1, row; row = table.rows[i]; i++) {
               //iterate through rows
               //rows would be accessed using the "row" variable assigned in the for loop
               var td_name = row.cells[1].innerHTML;
               var td_sip = row.cells[2].innerHTML;
               if ($('#edit-name').val().toLowerCase() == td_name.toLowerCase()) {
                    $('#errormsg-edit-acct').html("Account already exists");
                    e.preventDefault();
                }
            }
        })
    </script>
</body>

</html>